/// Noise generated by the OS or other apps, never something a rule should
/// see: Finder's folder metadata cache, AppleDouble resource forks (common
/// on network/exFAT volumes), and Microsoft Office's lock files for an open
/// document. Shared by the watcher and the Dry Run/Run Now folder scan so
/// all three execution paths agree on what's visible.
enum SystemFileFilter {
    static func isExcluded(_ filename: String) -> Bool {
        filename == ".DS_Store" || filename.hasPrefix("._") || filename.hasPrefix("~$")
    }
}
